"""Add listen time to station

Revision ID: 30f04c4e93c9
Revises: 627c19c2a4d3
Create Date: 2025-11-02 01:15:57.369677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30f04c4e93c9"
down_revision: Union[str, None] = "627c19c2a4d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stations", sa.Column("listen_time", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stations", "listen_time")
    # ### end Alembic commands ###
